# Yarn Configuration for amicaenv
# This file configures Yarn behavior for cleaner output and better dependency management

# Node modules linker
nodeLinker: node-modules

# Enable zero-installs (optional, can be disabled)
enableGlobalCache: false

# Suppress warnings for known issues
logFilters:
  - code: YN0002 # Missing peer dependencies
    level: discard
  - code: YN0006 # Deprecated packages
    level: info
  - code: YN0013 # Resolution warnings
    level: info

# Network settings
httpTimeout: 60000
networkTimeout: 60000

# Package manager optimizations
preferInteractive: true
enableInlineBuilds: true

# Support for workspaces
defaultSemverRangePrefix: "^"